workflows:
  flutter-build:
    name: Flutter Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods (for iOS)
        script: |
          cd ios
          pod install
          cd ..
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS
        script: flutter build ios --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/**/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
