// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpWKfGprBggjax8uGGOd4pCLeOGd4Ijg',
    appId: '1:1035140107927:web:924e8a1760aa2e8932e3d2',
    messagingSenderId: '1035140107927',
    projectId: 'masle-masail-2fb53',
    authDomain: 'masle-masail-2fb53.firebaseapp.com',
    storageBucket: 'masle-masail-2fb53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHctS0qwsVdU93bKssTZ_Lb7Ab6Sm94mk',
    appId: '1:1035140107927:android:64761b1b0dbe6c6832e3d2',
    messagingSenderId: '1035140107927',
    projectId: 'masle-masail-2fb53',
    storageBucket: 'masle-masail-2fb53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zLqw8Dw0PEHEOxcSoaMUdDosf631RtA',
    appId: '1:1035140107927:ios:b4874947830facf032e3d2',
    messagingSenderId: '1035140107927',
    projectId: 'masle-masail-2fb53',
    storageBucket: 'masle-masail-2fb53.firebasestorage.app',
    iosBundleId: 'com.quicode.maslemasail',
  );
}
